title: calebdperry.com
author:
  name: Caleb Perry
  email: 'calebperry4@gmail.com'
metadata:
    description: 'Caleb Perry | Full Stack Developer'
header:
  title: "Caleb Perry"
  description: "Full Stack Developer, Splunk App Developer"